# Generated by Django 5.0.7 on 2024-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tank',
            field=models.IntegerField(default=10000),
        ),
    ]
