# Generated by Django 5.0.7 on 2024-07-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_alter_inventory_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='fullcharge',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rocket',
            field=models.IntegerField(default=3),
        ),
    ]
