# Generated by Django 5.0.7 on 2024-07-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0004_inventory_rocket_active_inventory_rocket_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='current_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reward',
            name='last_reward_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
