# Generated by Django 5.0.7 on 2024-07-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0005_reward_current_day_reward_last_reward_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='current_day',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='last_reward_date',
        ),
        migrations.AddField(
            model_name='reward',
            name='played_hamster_kombat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reward',
            name='subscribed_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reward',
            name='watched_av_video',
            field=models.BooleanField(default=False),
        ),
    ]
