# Generated by Django 5.0.7 on 2024-07-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0006_remove_reward_current_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='check_daily_reward',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='luckywheel',
        ),
        migrations.AddField(
            model_name='reward',
            name='invited_friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_by', to='Front.user'),
        ),
    ]
